services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rpass
      MYSQL_DATABASE: siso_sti_db
      MYSQL_USER: ruser
      MYSQL_PASSWORD: rpass
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro  # Aqu√≠ montas el archivo
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - siso_net

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      DB_HOST: mysql
      DB_USER: ruser
      DB_PASS: rpass
      DB_NAME: siso_sti_db
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306", "--", "npm", "start"]
    networks:
      - siso_net

  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "80"  
    depends_on:
      - backend
    networks:
      - siso_net

  plumber:
    build: ./plumber-api
    container_name: plumber
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_USER: ruser
      DB_PASS: rpass
      DB_NAME: siso_sti_db
    depends_on:
      - mysql
    networks:
      - siso_net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
      - plumber
    networks:
      - siso_net

volumes:
  mysql-data:

networks:
  siso_net:
